version: "3"

services:
  postgres:
    image: postgres:10-alpine
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=parking
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    ports:
      - "5432:5432"
    healthcheck:
      test: "exit 0"

  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@user.com
  #     - PGADMIN_DEFAULT_PASSWORD=123456
  #   ports:
  #     - "9001:80"
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   links:
  #     - postgres

  adminer:
    image: adminer
    restart: always
    environment:
      - ADMINER_DEFAULT_SYSTEM=pgsql
      - ADMINER_DEFAULT_SERVER=postgres
      - ADMINER_DESIGN='nette'
    ports:
      - 8082:8080
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres

volumes:
  pgdata:
